version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: sriharika94/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  backend:
    image: sriharika94/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  
  frontend:
    image: sriharika94/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend



# docker compose up -d  creates all containers
# docker copmose down -d removes all
